In [1]:
#!pip install statsbombpy

In [2]:
from statsbombpy import sb

In [84]:
import pandas as pd

In [242]:
import numpy as np

In [3]:
sb.competitions()

C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,16,4,Europe,Champions League,male,False,False,2018/2019,2023-03-07T12:20:48.118250,2021-06-13T16:17:31.694,None,2023-03-07T12:20:48.118250
1,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
2,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
3,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,26,Europe,Champions League,male,False,False,2014/2015,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
5,16,25,Europe,Champions League,male,False,False,2013/2014,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
6,16,24,Europe,Champions League,male,False,False,2012/2013,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-07-10T13:41:45.751
7,16,23,Europe,Champions League,male,False,False,2011/2012,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
8,16,22,Europe,Champions League,male,False,False,2010/2011,2022-01-26T21:07:11.033473,2021-06-13T16:17:31.694,None,2022-01-26T21:07:11.033473
9,16,21,Europe,Champions League,male,False,False,2009/2010,2022-11-15T17:26:10.871011,2021-06-13T16:17:31.694,None,2022-11-15T17:26:10.871011
10,16,41,Europe,Champions League,male,False,False,2008/2009,2021-11-07T14:20:01.699993,2021-06-13T16:17:31.694,None,2021-11-07T14:20:01.699993
11,16,39,Europe,Champions League,male,False,False,2006/2007,2021-03-31T04:18:30.437060,2021-06-13T16:17:31.694,None,2021-03-31T04:18:30.437060
12,16,37,Europe,Champions League,male,False,False,2004/2005,2021-04-01T06:18:57.459032,2021-06-13T16:17:31.694,None,2021-04-01T06:18:57.459032
13,16,44,Europe,Champions League,male,False,False,2003/2004,2022-11-24T21:06:10.454916,2021-06-13T16:17:31.694,None,2022-11-24T21:06:10.454916
14,16,76,Europe,Champions League,male,False,False,1999/2000,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
15,16,277,Europe,Champions League,male,False,False,1972/1973,2023-07-06T12:49:07.467625,None,None,2023-07-06T12:49:07.467625
16,16,71,Europe,Champions League,male,False,False,1971/1972,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
17,16,276,Europe,Champions League,male,False,False,1970/1971,2023-07-06T12:50:01.961048,None,None,2023-07-06T12:50:01.961048
18,87,279,Spain,Copa del Rey,male,False,False,1977/1978,2023-06-26T10:36:15.442581,None,None,2023-06-26T10:36:15.442581
19,37,90,England,FA Women's Super League,female,False,False,2020/2021,2023-02-25T14:52:09.326729,2021-06-13T16:17:31.694,None,2023-02-25T14:52:09.326729
20,37,42,England,FA Women's Super League,female,False,False,2019/2020,2023-02-25T12:45:18.376026,2021-06-13T16:17:31.694,None,2023-02-25T12:45:18.376026
21,37,4,England,FA Women's Super League,female,False,False,2018/2019,2022-12-01T11:41:40.025541,2021-06-13T16:17:31.694,None,2022-12-01T11:41:40.025541
22,43,106,International,FIFA World Cup,male,False,True,2022,2023-07-15T22:01:09.812380,2023-07-15T22:01:52.119586,2023-07-15T22:01:52.119586,2023-07-15T22:01:09.812380
23,43,3,International,FIFA World Cup,male,False,True,2018,2022-09-05T17:17:56.670896,2021-06-13T16:17:31.694,None,2022-09-05T17:17:56.670896
24,43,51,International,FIFA World Cup,male,False,True,1974,2023-07-17T23:19:58.853207,2021-06-13T16:17:31.694,None,2023-07-17T23:19:58.853207
25,1238,108,India,Indian Super league,male,False,False,2021/2022,2023-03-31T02:14:09.896947,None,None,2023-03-31T02:14:09.896947
26,11,90,Spain,La Liga,male,False,False,2020/2021,2022-12-05T14:39:07.366723,2023-04-28T08:23:01.474542,2023-04-28T08:23:01.474542,2022-12-05T14:39:07.366723
27,11,42,Spain,La Liga,male,False,False,2019/2020,2023-04-19T10:52:22.240135,2021-06-13T16:17:31.694,None,2023-04-19T10:52:22.240135
28,11,4,Spain,La Liga,male,False,False,2018/2019,2023-07-11T21:28:41.642817,2021-07-09T14:53:22.103024,None,2023-07-11T21:28:41.642817
29,11,1,Spain,La Liga,male,False,False,2017/2018,2023-04-25T00:10:26.116531,2021-06-13T16:17:31.694,None,2023-04-25T00:10:26.116531
30,11,2,Spain,La Liga,male,False,False,2016/2017,2023-05-11T08:13:40.117646,2021-06-13T16:17:31.694,None,2023-05-11T08:13:40.117646
31,11,27,Spain,La Liga,male,False,False,2015/2016,2023-02-21T15:55:07.071365,2021-06-13T16:17:31.694,None,2023-02-21T15:55:07.071365
32,11,26,Spain,La Liga,male,False,False,2014/2015,2022-08-14T18:49:03.341489,2021-06-13T16:17:31.694,None,2022-08-14T18:49:03.341489
33,11,25,Spain,La Liga,male,False,False,2013/2014,2022-07-23T12:18:49.547396,2021-06-13T16:17:31.694,None,2022-07-23T12:18:49.547396
34,11,24,Spain,La Liga,male,False,False,2012/2013,2022-09-25T20:52:24.444609,2021-06-13T16:17:31.694,None,2022-09-25T20:52:24.444609
35,11,23,Spain,La Liga,male,False,False,2011/2012,2022-12-01T14:10:17.791769,2021-06-13T16:17:31.694,None,2022-12-01T14:10:17.791769
36,11,22,Spain,La Liga,male,False,False,2010/2011,2023-04-19T10:48:44.079830,2021-06-13T16:17:31.694,None,2023-04-19T10:48:44.079830
37,11,21,Spain,La Liga,male,False,False,2009/2010,2023-04-19T10:48:01.770383,2021-06-13T16:17:31.694,None,2023-04-19T10:48:01.770383
38,11,41,Spain,La Liga,male,False,False,2008/2009,2023-04-19T10:46:29.203565,2021-06-13T16:17:31.694,None,2023-04-19T10:46:29.203565
39,11,40,Spain,La Liga,male,False,False,2007/2008,2023-04-19T10:42:35.284291,2021-06-13T16:17:31.694,None,2023-04-19T10:42:35.284291
40,11,39,Spain,La Liga,male,False,False,2006/2007,2023-03-26T23:19:39.125951,2021-06-13T16:17:31.694,None,2023-03-26T23:19:39.125951
41,11,38,Spain,La Liga,male,False,False,2005/2006,2022-07-03T12:34:31.749038,2021-06-13T16:17:31.694,None,2022-07-03T12:34:31.749038
42,11,37,Spain,La Liga,male,False,False,2004/2005,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
43,11,278,Spain,La Liga,male,False,False,1973/1974,2023-07-06T12:50:48.807820,None,None,2023-07-06T12:50:48.807820
44,49,3,United States of America,NWSL,female,False,False,2018,2023-04-19T10:28:36.824565,2021-06-13T16:17:31.694,None,2023-04-19T10:28:36.824565
45,2,27,England,Premier League,male,False,False,2015/2016,2023-07-12T13:59:45.191483,2021-06-13T16:17:31.694,None,2023-07-12T13:59:45.191483
46,2,44,England,Premier League,male,False,False,2003/2004,2023-03-11T10:52:12.579230,2021-06-13T16:17:31.694,None,2023-03-11T10:52:12.579230
47,55,43,Europe,UEFA Euro,male,False,True,2020,2023-02-24T21:26:47.128979,2023-04-27T22:38:34.970148,2023-04-27T22:38:34.970148,2023-02-24T21:26:47.128979
48,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2023-07-17T21:19:03.032991,2023-07-17T21:21:56.497106,2023-07-17T21:21:56.497106,2023-07-17T21:19:03.032991
49,72,30,International,Women's World Cup,female,False,True,2019,2023-04-07T09:00:52.515359,2021-06-13T16:17:31.694,None,2023-04-07T09:00:52.515359

In [86]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [260]:
#ordering leicester city's matches and filtering them out from all the games in the season

x=sb.matches(competition_id=2, season_id=27)
x=x[(x.home_team=='Leicester City')|(x.away_team=='Leicester City')].sort_values(by='match_date')

C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [261]:
leicester_matches=x.match_id
# leicester_matches

In [262]:
x

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
124,3754237,2015-08-08,16:00:00.000,England - Premier League,2015/2016,Leicester City,Sunderland,4,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,King Power Stadium,Lee Mason,Claudio Ranieri,Dick Advocaat,1.1.0,2,2
178,3754203,2015-08-15,16:00:00.000,England - Premier League,2015/2016,West Ham United,Leicester City,1,2,available,...,2021-06-13T16:17:31.694,2,Regular Season,Boleyn Ground,Anthony Taylor,Slaven Bilić,Claudio Ranieri,1.1.0,2,2
183,3753987,2015-08-22,16:00:00.000,England - Premier League,2015/2016,Leicester City,Tottenham Hotspur,1,1,available,...,2021-06-13T16:17:31.694,3,Regular Season,King Power Stadium,Martin Atkinson,Claudio Ranieri,Mauricio Roberto Pochettino Trossero,1.1.0,2,2
41,3754023,2015-08-29,16:00:00.000,England - Premier League,2015/2016,AFC Bournemouth,Leicester City,1,1,available,...,2021-06-13T16:17:31.694,4,Regular Season,Vitality Stadium,Neil Swarbrick,Eddie Howe,Claudio Ranieri,1.1.0,2,2
67,3754106,2015-09-13,17:00:00.000,England - Premier League,2015/2016,Leicester City,Aston Villa,3,2,available,...,2021-06-13T16:17:31.694,5,Regular Season,King Power Stadium,Mike Dean,Claudio Ranieri,Tim Sherwood,1.1.0,2,2
21,3754146,2015-09-19,16:00:00.000,England - Premier League,2015/2016,Stoke City,Leicester City,2,2,available,...,2021-06-13T16:17:31.694,6,Regular Season,bet365 Stadium,Andre Marriner,Mark Hughes,Claudio Ranieri,1.1.0,2,2
83,3754174,2015-09-26,16:00:00.000,England - Premier League,2015/2016,Leicester City,Arsenal,2,5,available,...,2021-06-13T16:17:31.694,7,Regular Season,King Power Stadium,Craig Pawson,Claudio Ranieri,Arsène Wenger,1.1.0,2,2
145,3754335,2015-10-03,16:00:00.000,England - Premier League,2015/2016,Norwich City,Leicester City,1,2,available,...,2021-06-13T16:17:31.694,8,Regular Season,Carrow Road,Mark Clattenburg,Alex Neil,Claudio Ranieri,1.1.0,2,2
159,3754302,2015-10-17,16:00:00.000,England - Premier League,2015/2016,Southampton,Leicester City,2,2,available,...,2021-06-13T16:17:31.694,9,Regular Season,St. Mary''s Stadium,Paul Tierney,Ronald Koeman,Claudio Ranieri,1.1.0,2,2
135,3754263,2015-10-24,16:00:00.000,England - Premier League,2015/2016,Leicester City,Crystal Palace,1,0,available,...,2021-06-13T16:17:31.694,10,Regular Season,King Power Stadium,Mike Dean,Claudio Ranieri,Alan Pardew,1.1.0,2,2
40,3754006,2015-10-31,16:00:00.000,England - Premier League,2015/2016,West Bromwich Albion,Leicester City,2,3,available,...,2021-06-13T16:17:31.694,11,Regular Season,The Hawthorns,Anthony Taylor,Tony Pulis,Claudio Ranieri,1.1.0,2,2
169,3754156,2015-11-07,16:00:00.000,England - Premier League,2015/2016,Leicester City,Watford,2,1,available,...,2021-06-13T16:17:31.694,12,Regular Season,King Power Stadium,Roger East,Claudio Ranieri,Enrique Sánchez Flores,1.1.0,2,2
101,3754211,2015-11-21,16:00:00.000,England - Premier League,2015/2016,Newcastle United,Leicester City,0,3,available,...,2021-06-13T16:17:31.694,13,Regular Season,St. James'' Park,Mike Jones,Steve McClaren,Claudio Ranieri,1.1.0,2,2
95,3754186,2015-11-28,18:30:00.000,England - Premier League,2015/2016,Leicester City,Manchester United,1,1,available,...,2021-06-13T16:17:31.694,14,Regular Season,King Power Stadium,Craig Pawson,Claudio Ranieri,Louis van Gaal,1.1.0,2,2
60,3754085,2015-12-05,16:00:00.000,England - Premier League,2015/2016,Swansea City,Leicester City,0,3,available,...,2021-06-13T16:17:31.694,15,Regular Season,Swansea.com Stadium,Michael Oliver,Garry Monk,Claudio Ranieri,1.1.0,2,2
160,3754013,2015-12-14,21:00:00.000,England - Premier League,2015/2016,Leicester City,Chelsea,2,1,available,...,2021-06-13T16:17:31.694,16,Regular Season,King Power Stadium,Mark Clattenburg,Claudio Ranieri,José Mario Felix dos Santos Mourinho,1.1.0,2,2
100,3754166,2015-12-19,16:00:00.000,England - Premier League,2015/2016,Everton,Leicester City,2,3,available,...,2021-06-13T16:17:31.694,17,Regular Season,Goodison Park,Jonathan Moss,Roberto Martínez Montoliú,Claudio Ranieri,1.1.0,2,2
163,3754343,2015-12-26,16:00:00.000,England - Premier League,2015/2016,Liverpool,Leicester City,1,0,available,...,2021-06-13T16:17:31.694,18,Regular Season,Anfield,Martin Atkinson,Jürgen Klopp,Claudio Ranieri,1.1.0,2,2
8,3754045,2015-12-29,20:45:00.000,England - Premier League,2015/2016,Leicester City,Manchester City,0,0,available,...,2021-06-12T16:17:31.694,19,Regular Season,King Power Stadium,Craig Pawson,Claudio Ranieri,Manuel Luis Pellegrini Ripamonti,1.1.0,2,2
0,3754058,2016-01-02,16:00:00.000,England - Premier League,2015/2016,Leicester City,AFC Bournemouth,0,0,available,...,2021-06-12T16:17:31.694,20,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Eddie Howe,1.1.0,2,2
189,3754065,2016-01-13,21:00:00.000,England - Premier League,2015/2016,Tottenham Hotspur,Leicester City,0,1,available,...,2021-06-12T16:17:31.694,21,Regular Season,White Hart Lane,Lee Mason,Mauricio Roberto Pochettino Trossero,Claudio Ranieri,1.1.0,2,2
319,3754250,2016-01-16,18:30:00.000,England - Premier League,2015/2016,Aston Villa,Leicester City,1,1,available,...,2021-06-12T16:17:31.694,22,Regular Season,Villa Park,Roger East,Rémi Garde,Claudio Ranieri,1.1.0,2,2
367,3754341,2016-01-23,16:00:00.000,England - Premier League,2015/2016,Leicester City,Stoke City,3,0,available,...,2021-06-12T16:17:31.694,23,Regular Season,King Power Stadium,Mike Dean,Claudio Ranieri,Mark Hughes,1.1.0,2,2
331,3754275,2016-02-02,20:45:00.000,England - Premier League,2015/2016,Leicester City,Liverpool,2,0,available,...,2021-06-12T16:17:31.694,24,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Jürgen Klopp,1.1.0,2,2
338,3754290,2016-02-06,13:45:00.000,England - Premier League,2015/2016,Manchester City,Leicester City,1,3,available,...,2021-06-12T16:17:31.694,25,Regular Season,Etihad Stadium,Anthony Taylor,Manuel Luis Pellegrini Ripamonti,Claudio Ranieri,1.1.0,2,2
324,3754261,2016-02-14,13:00:00.000,England - Premier League,2015/2016,Arsenal,Leicester City,2,1,available,...,2021-06-12T16:17:31.694,26,Regular Season,Emirates Stadium,Martin Atkinson,Arsène Wenger,Claudio Ranieri,1.1.0,2,2
10,3754049,2016-02-27,16:00:00.000,England - Premier League,2015/2016,Leicester City,Norwich City,1,0,available,...,2021-06-12T16:17:31.694,27,Regular Season,King Power Stadium,Neil Swarbrick,Claudio Ranieri,Alex Neil,1.1.0,2,2
310,3754231,2016-03-01,20:45:00.000,England - Premier League,2015/2016,Leicester City,West Bromwich Albion,2,2,available,...,2021-06-12T16:17:31.694,28,Regular Season,King Power Stadium,Mark Clattenburg,Claudio Ranieri,Tony Pulis,1.1.0,2,2
337,3754289,2016-03-05,18:30:00.000,England - Premier League,2015/2016,Watford,Leicester City,0,1,available,...,2021-06-12T16:17:31.694,29,Regular Season,Vicarage Road,Jonathan Moss,Enrique Sánchez Flores,Claudio Ranieri,1.1.0,2,2
208,3754002,2016-03-14,21:00:00.000,England - Premier League,2015/2016,Leicester City,Newcastle United,1,0,available,...,2021-06-12T16:17:31.694,30,Regular Season,King Power Stadium,Craig Pawson,Claudio Ranieri,Rafael Benítez Maudes,1.1.0,2,2
285,3754181,2016-03-19,16:00:00.000,England - Premier League,2015/2016,Crystal Palace,Leicester City,0,1,available,...,2021-06-12T16:17:31.694,31,Regular Season,Selhurst Park,Mike Jones,Alan Pardew,Claudio Ranieri,1.1.0,2,2
198,3753982,2016-04-03,14:30:00.000,England - Premier League,2015/2016,Leicester City,Southampton,1,0,available,...,2021-06-12T16:17:31.694,32,Regular Season,King Power Stadium,Michael Oliver,Claudio Ranieri,Ronald Koeman,1.1.0,2,2
270,3754152,2016-04-10,14:30:00.000,England - Premier League,2015/2016,Sunderland,Leicester City,0,2,available,...,2021-06-12T16:17:31.694,33,Regular Season,Stadium of Light,Anthony Taylor,Sam Allardyce,Claudio Ranieri,1.1.0,2,2
307,3754227,2016-04-17,14:30:00.000,England - Premier League,2015/2016,Leicester City,West Ham United,2,2,available,...,2021-06-12T16:17:31.694,34,Regular Season,King Power Stadium,Jonathan Moss,Claudio Ranieri,Slaven Bilić,1.1.0,2,2
308,3754228,2016-04-24,17:15:00.000,England - Premier League,2015/2016,Leicester City,Swansea City,4,0,available,...,2021-06-12T16:17:31.694,35,Regular Season,King Power Stadium,Mark Clattenburg,Claudio Ranieri,Francesco Guidolin,1.1.0,2,2
278,3754165,2016-05-01,15:05:00.000,England - Premier League,2015/2016,Manchester United,Leicester City,1,1,available,...,2021-06-12T16:17:31.694,36,Regular Season,Old Trafford,Michael Oliver,Louis van Gaal,Claudio Ranieri,1.1.0,2,2
224,3754033,2016-05-07,18:30:00.000,England - Premier League,2015/2016,Leicester City,Everton,3,1,available,...,2021-06-12T16:17:31.694,37,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Roberto Martínez Montoliú,1.1.0,2,2
309,3754229,2016-05-15,16:00:00.000,England - Premier League,2015/2016,Chelsea,Leicester City,1,1,available,...,2021-06-12T16:17:31.694,38,Regular Season,Stamford Bridge,Craig Pawson,Guus Hiddink,Claudio Ranieri,1.1.0,2,2

In [264]:
#creating a dataframe of players based on appearances in the league
a=pd.DataFrame()
for i in x.match_id:
    a=pd.concat([a, sb.lineups(match_id=i)['Leicester City'][['player_name', 'positions']]])

C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [265]:
a.positions=a.positions.apply(lambda x : x[0] if len(x)>0 else x)

In [266]:
a.positions.iloc[0]

{'position_id': 12,
 'position': 'Right Midfield',
 'from': '00:00',
 'to': None,
 'from_period': 1,
 'to_period': None,
 'start_reason': 'Starting XI',
 'end_reason': 'Final Whistle'}

In [279]:
l=pd.DataFrame()
l=a.positions.apply(pd.Series)

C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  l=a.positions.apply(pd.Series)
C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\2327907656.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

In [280]:
l['player_name']=a.player_name

In [287]:
l=l[~l.start_reason.isna()]

In [303]:
l

,position_id,position,from,to,from_period,to_period,start_reason,end_reason,player_name
0,12.0,Right Midfield,00:00,None,1.0,NaN,Starting XI,Final Whistle,Marc Albrighton
1,6.0,Left Back,00:00,None,1.0,NaN,Starting XI,Final Whistle,Jeffrey Schlupp
2,15.0,Left Center Midfield,00:00,None,1.0,NaN,Starting XI,Final Whistle,Danny Drinkwater
3,13.0,Right Center Midfield,00:00,None,1.0,NaN,Starting XI,Final Whistle,Andrew Philip King
5,22.0,Right Center Forward,00:00,None,1.0,NaN,Starting XI,Final Whistle,Shinji Okazaki
...,...,...,...,...,...,...,...,...,...
12,17.0,Right Wing,00:00,79:59,1.0,2.0,Starting XI,Substitution - Off (Tactical),Riyad Mahrez
13,1.0,Goalkeeper,00:00,None,1.0,NaN,Starting XI,Final Whistle,Kasper Schmeichel
14,13.0,Right Center Midfield,00:00,82:36,1.0,2.0,Starting XI,Tactical Shift,N''Golo Kanté
15,3.0,Right Center Back,00:00,None,1.0,NaN,Starting XI,Final Whistle,Marcin Ryszard Wasilewski
16,23.0,Center Forward,00:00,None,1.0,NaN,Starting XI,Final Whistle,Jamie Vardy

In [489]:
#selecting all events from the season
events = sb.competition_events(country="England", division= "Premier League", season="2015/2016", gender="male")

In [335]:
#events[events.team=='Leicester City']

In [490]:
#grouping all events from the season to perform season-wide statistical analysis and comparison
grouped_events = sb.competition_events(
    country="England",
    division= "Premier League",
    season="2015/2016",
    split=True)

C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [336]:
#grouped_events

In [491]:
#Calculating the Goals For (GF), Goals Against, and Win-Draw-Loss Record for each team

y=sb.matches(competition_id=2, season_id=27)
y=y[["home_score", "away_score", "home_team", "away_team"]]

C:\Users\CEPL\anaconda3\lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [781]:
gf=[]
ga=[]
pts=[]
w=[]
d=[]
l=[]

In [782]:
#Creating a DataFrame for the final PL Table
table=pd.DataFrame()
table['team']=y.home_team.unique()

In [783]:
for i in table.team:
    wins=0
    draws=0
    c=0
    a=y[y.home_team==i]
    hs=sum(a.home_score)
    hc=sum(a.away_score)
    for f in a.reset_index().index:
        if a.home_score.iloc[f]>a.away_score.iloc[f]:
            wins+=1
            c+=3
        elif a.home_score.iloc[f]==a.away_score.iloc[f]:
            draws+=1
            c+=1
    b=y[y.away_team==i]
    aws=sum(b.away_score)
    awc=sum(b.home_score)
    for f in b.reset_index().index:
        if b.away_score.iloc[f]>b.home_score.iloc[f]:
            wins+=1
            c+=3
        elif b.away_score.iloc[f]==b.home_score.iloc[f]:
            draws+=1
            c+=1
    gf.append((hs+aws))
    ga.append(hc+awc)
    w.append(wins)
    d.append(draws)
    pts.append(c)

In [784]:
table['gf']=gf
table['ga']=ga
table['gd']=table.gf-table.ga
table['w']=w
table['d']=d
table['l']=0
table['points']=pts

In [785]:
table.l=38-table.w-table.d

In [786]:
table=table.sort_values(by='points', ascending=False).reset_index().drop(columns='index')

In [787]:
#The premier league table for the 2015/16 season

table

                    team  gf  ga  gd   w   d   l  points
0         Leicester City  68  36  32  23  12   3      81
1                Arsenal  65  36  29  20  11   7      71
2      Tottenham Hotspur  69  35  34  19  13   6      70
3        Manchester City  71  41  30  19   9  10      66
4      Manchester United  49  35  14  19   9  10      66
5            Southampton  59  41  18  18   9  11      63
6        West Ham United  65  51  14  16  14   8      62
7              Liverpool  63  50  13  16  12  10      60
8             Stoke City  41  55 -14  14   9  15      51
9                Chelsea  59  53   6  12  14  12      50
10          Swansea City  42  52 -10  12  11  15      47
11               Everton  59  55   4  11  14  13      47
12               Watford  40  50 -10  12   9  17      45
13  West Bromwich Albion  34  48 -14  10  13  15      43
14        Crystal Palace  39  51 -12  11   9  18      42
15       AFC Bournemouth  45  67 -22  11   9  18      42
16            Sunderland  48  62 -14   9  12  17      39
17      Newcastle United  44  65 -21   9  10  19      37
18          Norwich City  39  67 -28   9   7  22      34
19           Aston Villa  27  76 -49   3   8  27      17

In [788]:
#Listing the top 6 teams in the PL for the 2015-16 season

top_six=["Leicester City", "Arsenal", "Tottenham Hotspur", "Manchester City", "Manchester United", "Southampton"]

In [789]:
#events[events.team.isin(top_six)]

In [790]:
#checking percentage of event columns that are null
for i in events.columns:
    print(i,'----->', round(events[i].isna().sum()/len(events)*100, 2),'%')

50_50 -----> 99.96 %
bad_behaviour_card -----> 99.99 %
ball_receipt_outcome -----> 95.83 %
ball_recovery_offensive -----> 99.99 %
ball_recovery_recovery_failure -----> 99.78 %
block_deflection -----> 99.97 %
block_offensive -----> 99.98 %
block_save_block -----> 100.0 %
carry_end_location -----> 78.18 %
clearance_aerial_won -----> 99.66 %
clearance_body_part -----> 98.51 %
clearance_head -----> 99.16 %
clearance_left_foot -----> 99.76 %
clearance_other -----> 99.99 %
clearance_right_foot -----> 99.6 %
counterpress -----> 96.87 %
dribble_no_touch -----> 100.0 %
dribble_nutmeg -----> 99.96 %
dribble_outcome -----> 99.01 %
dribble_overrun -----> 99.94 %
duel_outcome -----> 98.88 %
duel_type -----> 97.7 %
duration -----> 26.53 %
foul_committed_advantage -----> 99.91 %
foul_committed_card -----> 99.92 %
foul_committed_offensive -----> 99.98 %
foul_committed_penalty -----> 100.0 %
foul_committed_type -----> 99.97 %
foul_won_advantage -----> 99.9 %
foul_won_defensive -----> 99.83 %
foul_won_penalty -----> 99.99 %
goalkeeper_body_part -----> 99.84 %
goalkeeper_end_location -----> 99.57 %
goalkeeper_lost_in_play -----> 100.0 %
goalkeeper_lost_out -----> 100.0 %
goalkeeper_outcome -----> 99.7 %
goalkeeper_penalty_saved_to_post -----> 100.0 %
goalkeeper_position -----> 99.38 %
goalkeeper_punched_out -----> 100.0 %
goalkeeper_saved_to_post -----> 100.0 %
goalkeeper_shot_saved_off_target -----> 100.0 %
goalkeeper_shot_saved_to_post -----> 100.0 %
goalkeeper_success_in_play -----> 100.0 %
goalkeeper_technique -----> 99.81 %
goalkeeper_type -----> 99.27 %
half_start_late_video_start -----> 100.0 %
id -----> 0.0 %
index -----> 0.0 %
injury_stoppage_in_chain -----> 99.99 %
interception_outcome -----> 99.34 %
location -----> 0.56 %
match_id -----> 0.0 %
minute -----> 0.0 %
miscontrol_aerial_won -----> 99.97 %
off_camera -----> 98.68 %
out -----> 99.15 %
pass_aerial_won -----> 99.3 %
pass_angle -----> 71.52 %
pass_assisted_shot_id -----> 99.42 %
pass_body_part -----> 73.47 %
pass_cross -----> 99.27 %
pass_cut_back -----> 99.93 %
pass_deflected -----> 99.97 %
pass_end_location -----> 71.52 %
pass_goal_assist -----> 99.94 %
pass_height -----> 71.52 %
pass_inswinging -----> 99.88 %
pass_length -----> 71.52 %
pass_miscommunication -----> 99.98 %
pass_no_touch -----> 99.98 %
pass_outcome -----> 93.88 %
pass_outswinging -----> 99.88 %
pass_recipient -----> 73.47 %
pass_shot_assist -----> 99.48 %
pass_straight -----> 99.98 %
pass_switch -----> 99.23 %
pass_technique -----> 99.6 %
pass_through_ball -----> 99.86 %
pass_type -----> 94.1 %
period -----> 0.0 %
play_pattern -----> 0.0 %
player -----> 0.33 %
player_id -----> 0.33 %
player_off_permanent -----> 100.0 %
position -----> 0.33 %
possession -----> 0.0 %
possession_team -----> 0.0 %
possession_team_id -----> 0.0 %
related_events -----> 3.9 %
second -----> 0.0 %
shot_aerial_won -----> 99.93 %
shot_body_part -----> 99.21 %
shot_deflected -----> 99.99 %
shot_end_location -----> 99.21 %
shot_first_time -----> 99.77 %
shot_follows_dribble -----> 100.0 %
shot_freeze_frame -----> 99.22 %
shot_key_pass_id -----> 99.42 %
shot_one_on_one -----> 99.96 %
shot_open_goal -----> 99.99 %
shot_outcome -----> 99.21 %
shot_redirect -----> 100.0 %
shot_saved_off_target -----> 100.0 %
shot_saved_to_post -----> 100.0 %
shot_statsbomb_xg -----> 99.21 %
shot_technique -----> 99.21 %
shot_type -----> 99.21 %
substitution_outcome -----> 99.85 %
substitution_replacement -----> 99.85 %
tactics -----> 99.9 %
team -----> 0.0 %
team_id -----> 0.0 %
timestamp -----> 0.0 %
type -----> 0.0 %
under_pressure -----> 79.37 %

In [791]:
#Listing important metrics for evaluation

m=["team","player","counterpress", "pass_type", "pass_goal_assist", "play_pattern", "shot_outcome", "shot_statsbomb_xg", "shot_technique", "shot_type", "tactics"]

In [792]:
events=events[events['team'].isin(top_six)]

In [795]:
xg=events[m].groupby('team').sum().reset_index()

C:\Users\CEPL\AppData\Local\Temp\ipykernel_20896\1718639801.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  xg=events[m].groupby('team').sum().reset_index()

In [830]:
t6=table.copy()
t6=t6[t6.team.isin(top_six)]

In [831]:
xg

                team  shot_statsbomb_xg
0            Arsenal          65.136126
1     Leicester City          66.282171
2    Manchester City          64.555055
3  Manchester United          42.198589
4        Southampton          54.223258
5  Tottenham Hotspur          62.356203

In [832]:
#Merging accumulated xg data into top 6 table

t6=pd.merge(on='team', left=t6, right=xg, how='inner')

In [833]:
t6=t6.rename(columns={"shot_statsbomb_xg":"xg"})

In [834]:
t6

                team  gf  ga  gd   w   d   l  points         xg
0     Leicester City  68  36  32  23  12   3      81  66.282171
1            Arsenal  65  36  29  20  11   7      71  65.136126
2  Tottenham Hotspur  69  35  34  19  13   6      70  62.356203
3    Manchester City  71  41  30  19   9  10      66  64.555055
4  Manchester United  49  35  14  19   9  10      66  42.198589
5        Southampton  59  41  18  18   9  11      63  54.223258

In [835]:
#creating a table for goals scored

goals=events[m][events.shot_outcome=="Goal"].groupby(['team','player']).agg({'shot_outcome':'count'})

In [836]:
goals=goals.sort_values(by=['team', 'shot_outcome'], ascending=False)

In [837]:
goals=goals[goals['shot_outcome']>5]

In [838]:
goals.rename(columns={'shot_outcome':'goals'}, inplace=True)

In [839]:
goals=goals.reset_index()

In [840]:
#Creating a table for assists made

assists=events[m][events.pass_goal_assist==True].groupby(['team','player']).agg({'pass_goal_assist':'count'})

In [841]:
assists=assists.sort_values(by=['team', 'pass_goal_assist'], ascending=False)

In [842]:
assists=assists[assists['pass_goal_assist']>3]

In [843]:
assists.rename(columns={'pass_goal_assist':'goals'}, inplace=True)

In [844]:
assists=assists.reset_index()

In [845]:
goals

                 team                             player  goals
0   Tottenham Hotspur                         Harry Kane     25
1   Tottenham Hotspur                      Bamidele Alli     10
2   Tottenham Hotspur        Christian Dannemann Eriksen      6
3         Southampton                     Graziano Pellè     11
4         Southampton                         Sadio Mané     11
5         Southampton                         Shane Long     10
6         Southampton                        Dušan Tadić      7
7   Manchester United                    Anthony Martial     11
8   Manchester United                  Wayne Mark Rooney      8
9   Manchester United            Juan Manuel Mata García      6
10    Manchester City  Sergio Leonel Agüero del Castillo     24
11    Manchester City          Kelechi Promise Iheanacho      8
12    Manchester City                    Kevin De Bruyne      7
13    Manchester City                Gnégnéri Yaya Touré      6
14    Manchester City                    Raheem Sterling      6
15     Leicester City                        Jamie Vardy     24
16     Leicester City                       Riyad Mahrez     17
17     Leicester City                José Leonardo Ulloa      6
18            Arsenal                     Olivier Giroud     16
19            Arsenal   Alexis Alejandro Sánchez Sánchez     13
20            Arsenal                         Mesut Özil      6

In [846]:
assists

                 team                            player  goals
0   Tottenham Hotspur       Christian Dannemann Eriksen     12
1   Tottenham Hotspur                     Bamidele Alli      8
2   Tottenham Hotspur                       Erik Lamela      8
3         Southampton                       Dušan Tadić     11
4         Southampton                    Graziano Pellè      6
5         Southampton                        Sadio Mané      6
6         Southampton                 James Ward-Prowse      4
7         Southampton                        Shane Long      4
8   Manchester United           Juan Manuel Mata García      5
9   Manchester United                 Wayne Mark Rooney      5
10    Manchester City         David Josué Jiménez Silva     10
11    Manchester City                   Kevin De Bruyne      9
12    Manchester City              Jesús Navas González      7
13     Leicester City                      Riyad Mahrez     10
14     Leicester City                  Danny Drinkwater      7
15     Leicester City                   Marc Albrighton      7
16     Leicester City                       Jamie Vardy      5
17     Leicester City                   Christian Fuchs      4
18            Arsenal                        Mesut Özil     19
19            Arsenal                    Olivier Giroud      6
20            Arsenal            Héctor Bellerín Moruno      5
21            Arsenal                      Aaron Ramsey      4
22            Arsenal  Alexis Alejandro Sánchez Sánchez      4

In [847]:
#Calculating passes per game for each top 6 team

passes=grouped_events["passes"]

In [848]:
p=passes[passes.possession_team.isin(top_six)].groupby('possession_team').agg({'id':'count'}).reset_index()

In [849]:
p=p.rename(columns={'possession_team':'team','id':'passes'})

In [850]:
t6=pd.merge(on='team', left=t6, right=p, how='inner')

In [851]:
t6['passes']=round(t6['passes']/38,2)

In [852]:
t6.xg=round(t6.xg,2)

In [853]:
t6

                team  gf  ga  gd   w   d   l  points     xg  passes
0     Leicester City  68  36  32  23  12   3      81  66.28  396.03
1            Arsenal  65  36  29  20  11   7      71  65.14  602.45
2  Tottenham Hotspur  69  35  34  19  13   6      70  62.36  542.95
3    Manchester City  71  41  30  19   9  10      66  64.56  589.71
4  Manchester United  49  35  14  19   9  10      66  42.20  581.84
5        Southampton  59  41  18  18   9  11      63  54.22  470.16

In [863]:
#Calculating more key metrics for all top six teams

grouped_events.keys()

dict_keys(['starting_xis', 'half_starts', 'passes', 'ball_receipts', 'carrys', 'pressures', 'dispossesseds', 'duels', 'shots', 'blocks', 'goal_keepers', 'ball_recoverys', 'miscontrols', 'clearances', 'dribbled_pasts', 'dribbles', 'interceptions', 'foul_committeds', 'foul_wons', 'half_ends', 'substitutions', 'injury_stoppages', 'tactical_shifts', 'shields', '50/50s', 'offsides', 'errors', 'bad_behaviours', 'referee_ball_drops', 'own_goal_againsts', 'own_goal_fors', 'player_offs', 'player_ons', 'team'])

In [855]:
shots=grouped_events["shots"]
dribbles=grouped_events['dribbles']
interceptions=grouped_events['interceptions']
fouls=grouped_events['foul_committeds']
errors=grouped_events['errors']
bad=grouped_events['bad_behaviours']

In [856]:
metrics=[shots,dribbles,interceptions,fouls,errors,bad]
mt=['shots','dribbles','interceptions','fouls','errors','bad_behaviour']

In [857]:
for f in range(len(metrics)):
    i=metrics[f]
    x=i[i.possession_team.isin(top_six)].groupby('possession_team').agg({'id':'count'}).reset_index()
    x=x.rename(columns={'possession_team':'team','id': mt[f]})
    t6=pd.merge(on='team', left=t6, right=x, how='inner')

In [858]:
for i in t6.columns:
    if i in mt:
        t6[i]=round(t6[i]/38,2)

In [859]:
t6

,team,gf,ga,gd,w,d,l,points,xg,passes,shots,dribbles,interceptions,fouls,errors,bad_behaviour
0,Leicester City,68,36,32,23,12,3,81,66.28,396.03,13.61,18.18,10.87,11.34,0.21,0.18
1,Arsenal,65,36,29,20,11,7,71,65.14,602.45,15.32,21.82,12.71,14.45,0.21,0.16
2,Tottenham Hotspur,69,35,34,19,13,6,70,62.36,542.95,17.24,19.47,12.37,12.24,0.24,0.13
3,Manchester City,71,41,30,19,9,10,66,64.56,589.71,16.05,20.21,14.63,12.79,0.45,0.11
4,Manchester United,49,35,14,19,9,10,66,42.20,581.84,11.47,18.08,14.37,12.89,0.18,0.08
5,Southampton,59,41,18,18,9,11,63,54.22,470.16,13.71,14.11,12.00,11.87,0.18,0.26

In [1]:
#Rendering relevant files to csv for further analysis and model building

In [870]:
prints=[shots,dribbles,interceptions,fouls,errors,bad, table, t6, goals, assists]
pts='shots,dribbles,interceptions,fouls,errors,bad,table,t6,goals,assists,events,grouped_events'
pts=pts.split(',')

In [871]:
for i in range(len(prints)):
    f=prints[i]
    f.to_csv(f'{pts[i]}.csv')